git support

diff --git a/bin/rancid-cvs.in b/bin/rancid-cvs.in
--- a/bin/rancid-cvs.in
+++ b/bin/rancid-cvs.in
@@ -87,27 +87,55 @@ cd $BASEDIR
 
 # RCS system
 RCSSYS=${RCSSYS:=cvs};
-if [ $RCSSYS != "cvs" -a $RCSSYS != "svn" ] ; then
-    echo "$RCSSYS is not a valid value for RCSSYS."
-    exit 1
-fi
+case $RCSSYS in
+    cvs | svn )
+	# we're good
+	;;
+    git )
+	# force $CVSROOT
+	CVSROOT=$BASEDIR/.git
+	;;
+    * )
+	echo "$RCSSYS is not a valid value for RCSSYS."
+	exit 1
+	;;
+esac
 
 # Top level CVS stuff
-if [ $RCSSYS = cvs ]; then
-    if [ ! -d $CVSROOT ]; then
-	cvs -d $CVSROOT init
-    fi
-else
-    if echo "$CVSROOT" | grep -q "://"; then
-	# do nothing because CVSROOT is some sort of a URL
-	# also assume the repository has already been provisioned
-	:
-    else
-	if ! svn ls "file://$CVSROOT" >/dev/null 2>&1; then
-	    svnadmin create $CVSROOT @SVN_FSTYPE@
-	fi
-	CVSROOT="file://$CVSROOT"
-    fi
+if [ ! -d $CVSROOT ]; then
+    case $RCSSYS in
+	cvs )
+            if [ ! -d $CVSROOT ]; then
+	        cvs -d $CVSROOT init
+            fi
+	    ;;
+	svn )
+            if echo "$CVSROOT" | grep -q "://"; then
+	        # do nothing because CVSROOT is some sort of a URL
+	        # also assume the repository has already been provisioned
+	        :
+            else
+	        if ! svn ls "file://$CVSROOT" >/dev/null 2>&1; then
+	            svnadmin create $CVSROOT @SVN_FSTYPE@
+	        fi
+	        CVSROOT="file://$CVSROOT"
+            fi
+	    ;;
+	git )
+	    # git does not use $CVSROOT, instead configs are stored in $BASEDIR
+	    (
+		flock -x 200
+		git init
+		rm -f .gitignore
+		echo "/logs" >> .gitignore
+		echo "/.lockfile" >> .gitignore
+		echo "*~" >> .gitignore
+		echo ".#*" >> .gitignore
+		echo "*.new" >> .gitignore
+		git add .gitignore
+		git commit -m "Initializing repository."
+	    ) 200>$BASEDIR/.lockfile
+    esac
 fi
 
 # Log dir
@@ -132,23 +160,50 @@ do
     if [ ! -d $DIR ]; then
 	mkdir -p $DIR
 	cd $DIR
-	if [ $RCSSYS = cvs ]; then
-	    cvs import -m "$GROUP" $GROUP new rancid
-	    cd $BASEDIR
-	    cvs checkout $GROUP
-	else
-	    svn import -m "$GROUP" . $CVSROOT/$GROUP
-	    cd $BASEDIR
-	    svn checkout $CVSROOT/$GROUP $GROUP
-	    cd $DIR
-	    svn update
-	fi
+	case $RCSSYS in
+	    cvs )
+		cvs import -m "$GROUP" $GROUP new rancid
+		cd $BASEDIR
+		cvs checkout $GROUP
+		;;
+	    svn )
+		svn import -m "$GROUP" . $CVSROOT/$GROUP
+		cd $BASEDIR
+		svn checkout $CVSROOT/$GROUP $GROUP
+                cd $DIR
+                svn update
+		;;
+	    git )
+		cd $BASEDIR
+		echo "$GROUP/routers.all" >> .gitignore
+		echo "$GROUP/routers.down" >> .gitignore
+		echo "$GROUP/routers.up" >> .gitignore
+		echo "$GROUP/routers.mail" >> .gitignore
+		echo "$GROUP/routers.added" >> .gitignore
+		echo "$GROUP/routers.deleted" >> .gitignore
+		echo "$GROUP/routers.single" >> .gitignore
+		echo "$GROUP/routers.up.missed" >> .gitignore
+		echo "$GROUP/routers.failed" >> .gitignore
+		(
+		    flock -x 200
+		    git add .gitignore
+		    git commit -m "Update .gitignore"
+		) 200>$BASEDIR/.lockfile
+		;;
+	esac
     fi
     cd $DIR
     if [ ! -d configs ]; then
 	mkdir configs
-	$RCSSYS add configs
-	$RCSSYS commit -m 'new' configs
+	case $RCSSYS in
+	    cvs | svn )
+		$RCSSYS add configs
+		$RCSSYS commit -m 'new' configs
+		;;
+	    git )
+		# nothing to be done here
+		;;
+	esac
     fi
 
     # main files
@@ -163,7 +218,18 @@ do
     fi
     if [ ! -f router.db ]; then
 	touch router.db
-	$RCSSYS add router.db
-	$RCSSYS commit -m 'new' router.db
+	case $RCSSYS in
+	    cvs | svn )
+		$RCSSYS add router.db
+		$RCSSYS commit -m 'new' router.db
+		;;
+	    git )
+		(
+		    flock -x 200
+		    git add router.db
+		    git commit -m "Initializing $GROUP"
+		) 200>$BASEDIR/.lockfile
+		;;
+	esac
     fi
 done
